Repository gnembon/fabric-carpet, pull requests merged in 2022-06, with the labels that each got.

#1455 fix #1454
  src/main/java/carpet/helpers/RedstoneWireTurbo.java
  src/main/java/carpet/mixins/RedstoneWireBlock_fastMixin.java
  src/main/resources/carpet.accesswidener
Labels: hi priority

#1404 Improve error message when commands fail to be added and make commands using the new system check for masking
  src/main/java/carpet/script/CarpetScriptHost.java
  src/main/java/carpet/script/CarpetScriptServer.java
Labels: scarpet

#1476 Making portal_timer and portal_cooldown return portal timer and portal cooldown in that order
  src/main/java/carpet/script/value/EntityValue.java
  src/main/resources/assets/carpet/scripts/ai_tracker.sc
Labels: bug, scarpet
