Repository gnembon/fabric-carpet, pull requests merged in 2022-10, with the labels that each got.

#1452 Fully remove scarpet commands when apps are unloaded
  src/main/java/carpet/fakes/CommandDispatcherInterface.java
  src/main/java/carpet/fakes/CommandNodeInterface.java
  src/main/java/carpet/mixins/CommandDispatcher_scarpetCommandsMixin.java
  src/main/java/carpet/mixins/CommandNode_scarpetCommandsMixin.java
  src/main/java/carpet/script/CarpetScriptHost.java
  src/main/java/carpet/script/CarpetScriptServer.java
  src/main/resources/carpet.mixins.json
Labels: scarpet

#1556 Expose origin-less constructors and methods
  src/main/java/carpet/script/CarpetContext.java
  src/main/java/carpet/script/CarpetEventServer.java
  src/main/java/carpet/script/CarpetScriptHost.java
  src/main/java/carpet/script/value/ScreenValue.java
Labels: scarpet

#1553 Fix `in` (`~`) operator producing broken values
  src/main/java/carpet/script/value/Value.java
Labels: bug, scarpet

#1574 Fixed NPE when events are triggered within events
  src/main/java/carpet/script/CarpetEventServer.java
Labels: hi priority, scarpet
